image: node:lts-alpine3.12
stages:
  - build
  - package
  - deploy
variables:
  PACKAGE_IMAGE: docker:19.03-git
  DEPLOY_IMAGE: alpine:3.12
  KUBECTL_URL: "https://storage.googleapis.com/kubernetes-release/release/v1.12.1/bin/linux/amd64/kubectl"
  DOCKER_DIND: docker:19.03-dind

build:
  stage: build
  before_script:
    - yarn install
  script:
    - yarn build
  artifacts:
    paths:
      - dist/*
    expire_in: 3 days
  only:
    - develop

package:
  stage: package
  image: $PACKAGE_IMAGE
  services:
    - $DOCKER_DIND
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - develop

deploy:
  stage: deploy
  image: $DEPLOY_IMAGE
  environment:
    name: development
  services:
    - $DOCKER_DIND
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  before_script:
    - echo "Start deploying ..."
  script:
    - apk update && apk add --no-cache curl
    - curl -LO $KUBECTL_URL
    - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p $HOME/.kube
    - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
    - sed -i "s#FRONTEND_IMAGE_TAG#$IMAGE_TAG#g" k8s.dev.yaml

    - kubectl --kubeconfig $HOME/.kube/config --namespace=YOUR_NAME_SPACE apply -f k8s.dev.yaml

    - kubectl --kubeconfig $HOME/.kube/config --namespace=YOUR_NAME_SPACE apply -f k8s.ingress.dev.yaml
  only:
    - develop
